baseURL = "https://example.com"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Arjun gandhi"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = ""

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[params]
title = "Arjun Gandhi"
author = "Arjun Gandhi"
#copyright = "2020-2021"
description = "I make things"
profilePicture = "images/profile.jpg"
keywords = ""
favicon = "favicons/"
# example ["css/custom.css"]
customCss = []
# example ["js/custom.js"]
customJs = [] 
mainSections = ["projects"]
images = ["images/site-feature-image.png"]
doNotLoadAnimations = false
# Form Spree Contact Form
# contactFormAction = "https://formspree.io/f/your-form-hash-here"
# Google Site Verify
# googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
# indexDateFormat = "Mon, Jan 2, 2006"
listDateFormat = "Jan, 2006"
# singleDateFormat = "Mon, Jan 2, 2006"
# Commento Comments
# CommentoURL = "https://commento.example.com/js/commento.js"
displayMode = "nord-dark"
disableThemeSwitcher = true

[params.simpleAnalytics]
# enable = true
# customurl = "https://analytics.example.com"

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/arjungandhi06/"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/arjungandhi"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:contact@arjungandhi.com"

## Menu items

[menu]

  [[menu.main]]
  name = "Who am I?"
  identifier = "whoami"
  weight = 100
  url = "/whoami"

  [[menu.main]]
  name = "Projects!"
  weight = 200
  identifier = "projects"
  url = "/projects/"

  [[menu.main]]
  name = "Contact"
  weight = 300
  identifier = "contact"
  url = "/contact/"


# Deployment
[deployment]

[[deployment.targets]]
name = "arjungandhi.com"
URL = "s3://arjungandhi.com?region=us-east-1"

# If you are using a CloudFront CDN, deploy will invalidate the cache as needed.
cloudFrontDistributionID =	"E357UXQ7R81NUT"

[[deployment.matchers]]
# Cache static assets for 20 years.
pattern = "^.+\\.(js|css|png|jpg|gif|svg|ttf)$"
cacheControl = "max-age=630720000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true
